const users = [
    {
        id: 1,
        name: "Hassan",
        email: "hassan@email.com",
        role: "nodejs",
        position: "intern",
        phone: "033312312312",
        isActive: true,
    },
    {
        id: 2,
        name: "Ali",
        email: "ali@email.com",
        role: "nodejs",
        position: "intern",
        phone: "033312312312",
        isActive: true,
    },
    {
        id: 3,
        name: "Umar",
        email: "umar@email.com",
        role: "nodejs",
        position: "intern",
        phone: "033312312312",
        isActive: true,
    },
    {
        id: 4,
        name: "Asad",
        email: "asad@email.com",
        role: "nodejs",
        position: "intern",
        phone: "033312312312",
        isActive: true,
    },
    {
        id: 5,
        name: "Harmen",
        email: "har@email.com",
        role: "nodejs",
        position: "intern",
        phone: "033312312312",
        isActive: true,
    },
    {
        id: 6,
        name: "Amir",
        email: "amir@email.com",
        role: "nodejs",
        position: "intern",
        phone: "033312312312",
        isActive: true,
    },
];
module.exports = { users };
